use_frameworks!

platform :ios, '10.0'

target 'Flexign_Example' do
  pod 'Flexign', :path => '../'

  target 'Flexign_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
